---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/docker-cpi

inputs:
  - name: bosh-deployment
  - name: stemcell

params:
  CPI_OPS_FILE: ~
  STEMCELL_NAME: ~

outputs:
  - name: bosh-deployment
    path: bosh-deployment-output

run:
  path: bosh-deployment/ci/tasks/update-stemcell.sh
